name: Build and Push Docker Image # Naam van de GitHub Action workflow #

on:
  push:
    branches:
      - main # Start de workflow bij pushes naar de 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Gebruik de laatste versie van Ubuntu voor de job runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Stap om de code van de repository te klonen

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # Stel Docker Buildx in, wat handig is voor het bouwen van multi-platform images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2 # Gebruik de Docker login actie om in te loggen bij GitHub Container Registry
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # Gebruik de GitHub actor voor authenticatie
        password: ${{ secrets.GH_TOKEN }} # Gebruik de GitHub token voor authenticatie

    - name: Log in to Docker Hub
      uses: docker/login-action@v2 # Gebruik de Docker login actie om in te loggen bij Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub gebruikersnaam
        password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub wachtwoord

    - name: Build and tag the Docker image
      run: |
        IMAGE_NAME_GHCR=ghcr.io/alpharubie/my-nginx-image
        IMAGE_NAME_DOCKERHUB=alpharubie/my-nginx-image

        # Bouw en tag de Docker image
        docker build -t $IMAGE_NAME_GHCR:latest -t $IMAGE_NAME_DOCKERHUB:latest .
        docker tag $IMAGE_NAME_GHCR:latest $IMAGE_NAME_GHCR:${{ github.sha }}
        docker tag $IMAGE_NAME_DOCKERHUB:latest $IMAGE_NAME_DOCKERHUB:${{ github.sha }}

    - name: Push the Docker image to GitHub Container Registry
      run: |
        IMAGE_NAME_GHCR=ghcr.io/alpharubie/my-nginx-image
        docker push $IMAGE_NAME_GHCR:latest
        docker push $IMAGE_NAME_GHCR:${{ github.sha }}

    - name: Push the Docker image to Docker Hub
      run: |
        IMAGE_NAME_DOCKERHUB=alpharubie/my-nginx-image
        docker push $IMAGE_NAME_DOCKERHUB:latest
        docker push $IMAGE_NAME_DOCKERHUB:${{ github.sha }}
