name: Build and Push Docker Image # Naam van de GitHub Action workflow

on:
  push:
    branches:
      - main # Start de workflow bij pushes naar de 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Gebruik de laatste versie van Ubuntu voor de job runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Stap om de code van de repository te klonen

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # Stel Docker Buildx in, wat handig is voor het bouwen van multi-platform images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2 # Gebruik de Docker login actie om in te loggen bij GitHub Container Registry
      with:
        username: ${{ github.actor }} # Gebruik de GitHub actor voor authenticatie
        password: ${{ secrets.GH_TOKEN }} # Gebruik de GitHub token voor authenticatie

    - name: Build and tag the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-nginx-image
        docker build -t $IMAGE_NAME:latest . # Bouw de Docker image en tag deze met 'latest'
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }} # Tag de gebouwde image met de huidige GitHub commit SHA

    - name: Push the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-nginx-image
        docker push $IMAGE_NAME:latest # Push de Docker image getagd met 'latest' naar GitHub Container Registry
        docker push $IMAGE_NAME:${{ github.sha }} # Push de Docker image getagd met de GitHub commit SHA naar GitHub Container Registry
